### ISSUE TITLE
Metrics precision

### ISSUE THREAD

**Issue by RodenLuo** [nanovis/DiffFit#26]
Hi @ondrejstrnad, Can you check how to set the number of decimal places for floats in the table? If you are gonna implement it, work on the point-cloud branch. Give `Density` 2 decimals and the rest 4. Thanks.

![image](https://github.com/user-attachments/assets/610c2366-eb6f-4c9f-9ce8-7860027614d6)

**Comment by ondrejstrnad** [comment]
Doable in tablemodel.data() function. For selected column(s) something like:
return QVariant(QString::number(float(record_row[index.column() + 4]), 'f', 2));
