### ISSUE TITLE
Automatically install CUDA enabled version of PyTorch on Windows

### ISSUE THREAD

**Issue by RodenLuo** [nanovis/DiffFit#40]
Hi Tom @tomgoddard, 

I tested the current latest release (v0.6.1) on both Linux and Windows. With Ubuntu 22.04, the cuda-enabled version of PyTorch was installed. But with Windows 11, the installed PyTorch was with CPU only. I tried a few workarounds but could not find an optimal solution, one without the user's manually typing commands. Could you please take a look and advise? Thanks! 

Possible solutions
---
1. The user needs the write permission in the ChimeraX installation path for this option.
    1. Uninstall DiffFit by `toolshed uninstall DiffFit`
    2. Make sure the installed PyTorch is deleted. In my test case, I need to delete the folders starting with `torch` under `C:\Users\luod\AppData\Local\UCSF\ChimeraX\1.8\Python311\site-packages`
    3. Go to the ChimeraX bin folder and open `cmd` from there
    4. Run `python.exe -m pip install torch==2.2.1 --index-url https://download.pytorch.org/whl/cu121`
    5. Reinstall DiffFit 
    6. One issue with this approach is that it changes ChimeraX's built-in Python site-packages.

2. The user needs to go to `Tools > General > Shell`, and run:
    1. `pip uninstall torch`
    2. `pip install torch==2.2.1 --index-url https://download.pytorch.org/whl/cu121`.
    3. There is still a problem, though. The ChimeraX window freezes forever after running either of the above commands, even though sometimes it has finished successfully.

**Comment by tomgoddard** [comment]
First the user should of course not have to reinstall torch themselves.  Almost no one will use DiffFit on Windows if you have to go through that monkey business.  It looks like you are having pip get the Cuda 12.1 version of torch.  Does that work if the user has Cuda 10 or Cuda 11 on their system.  What if the user has Cuda 12.5 on their system?  Do you know what the cuda compatibility requirements are?  I don't.  Assuming that your choice of cuda 12.1 is compatible with different cuda libraries installed on the user's computer, it seems you are just trying to install from a different PyPi repository.  I don't know if the ChimeraX bundle_info.xml or pyproject.toml can handle that.  I'll make a ChimeraX ticket asking about that.  Also did you know there is a "pip" ChimeraX command so it does require going to the Python shell?  But it does not have an option to specify where pip gets the package.

**Comment by tomgoddard** [comment]
I made the following ChimeraX ticket to get input from the ChimeraX Toolshed developers Zach and Greg about how to install torch from a specified repository

    https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/16220

**Comment by zjp** [comment]
I don't believe that `pyproject.toml` files allow a package maintainer to give a URL for a dependency. See [this comment on discuss.python.org](https://discuss.python.org/t/how-to-specify-extra-index-in-a-pyproject-toml-for-pip-and-pip-tools/23592/4). 

If torch is something that's going to stay static over the life of your package, you could:

1. vendor it - copy torch into your project and import it locally in your code
2. when your package starts up, import `run_logged_pip` from `chimerax.core.python_utils` and pass it `install --user -qq --upgrade-strategy only-if-needed --no-warn-script-location --index-url https://download.pytorch.org/whl/cu12 torch==2.2.1` 

See the kvfinder bundle for how Eric has done it before.

**Comment by tomgoddard** [comment]
The torch 2.2.1 Windows wheel from https://download.pytorch.org/whl/cu12 is over 2 Gbytes in size so probably not a good idea to try to include it in the DiffFit Toolshed wheel.

  -rw-r--r--@   1 goddard  staff  2473941180 Oct 30 13:11 torch-2.1.1+cu121-cp311-cp311-win_amd64.whl

But maybe Zach's second suggestion is the way to go.  Here is the ChimeraX code uses to pip install kvfinder from PyPi when the tool is first used.

    https://github.com/RBVI/ChimeraX/blob/develop/src/bundles/kvfinder/src/__init__.py

**Comment by RodenLuo** [comment]
Thanks very much, Tom, Zach, and Eric!

Fully agree that the user shouldn't have to go through any `cmd` stuff. Taking all of the abovementioned factors, as well as the fact that PyTorch's official guide requires the user to type in an index-url when using pip, into consideration, I have settled on using a Dependencies tab; see the screenshot below. In this way, the user only needs to click a button to resolve this matter, and if that doesn't work, the user can still consult PyTorch's official guide to find a different version or index-url. I changed a few details. I used a single `-q` to allow some level of log output and `--force-reinstall`. (Related commits: 8a34dbba5e506bae8c157c91eb0223e50071e243, eac672e8e33ef47c0e5154cc8c8cb2df2e90c279, d9a4fb494dcfc8ffe4236d9156d0de0ed4793c01)

![image](https://github.com/user-attachments/assets/6531373c-53be-40a8-9c2b-041b43314f41)

Glad to know the ChimeraX pip command, but it doesn't handle `pip list/show` (apart from `--index-url`). This Dependencies tab can be easily extended to a GUI package manager. The ChimeraX pip command can also be extended. But I feel this should be a ChimeraX-wide feature so as not to distract the users too much. (If you receive pull requests from GitHub and would like to have this feature, I'm happy to make one.)

Please feel free to comment or reopen the issue. 

#### About the CUDA versions

I'm not that deep with PyTorch, GPU, or CUDA. But here is my experience. With a freshly installed Win11 with an RTX 4090/8000/3090/3070, meaning that I don't have to install anything extra for CUDA, but I do have the graphics card driver correctly installed, DiffFit runs fine with these pip-installed PyTorch versions: 2.2.1+cu121, 2.5.1+cu118, 2.5.1+cu121, or 2.5.1+cu124. GeForce RTX 4090's compute capability is 8.9; Quadro RTX 8000's compute capability is 7.5. One can check CUDA compute capability at https://developer.nvidia.com/cuda-gpus.

Why don't I need to install anything extra for CUDA? Because pip installed PyTorch ships with the necessary CUDA runtime. This also partially explains why all three versions work fine. Because a different runtime version is shipped. This also means that both RTX 4090 and RTX 8000 support these CUDA versions.

Then, which CUDA version to choose? My practice is to try from the latest downwards.

What's the relationship between compute capability (CC) 8.9 or 7.5 and those CUDA versions? I rarely touch the relevance of the numbers for CC. My feeling/understanding is that this is a CUDA program developer's consideration rather than the users'. And every time, I don't have a strong feeling that I really understand it, with all the concepts of Min/Max CC and backward compatibility. But this page might be interesting to look at: https://stackoverflow.com/questions/28932864/which-compute-capability-is-supported-by-which-cuda-versions.
